// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: labtop_service.proto

package pc

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CreateLaptopRequest struct {
	Laptop               *Laptop  `protobuf:"bytes,1,opt,name=laptop,proto3" json:"laptop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLaptopRequest) Reset()         { *m = CreateLaptopRequest{} }
func (m *CreateLaptopRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLaptopRequest) ProtoMessage()    {}
func (*CreateLaptopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9cf9ee0377190e0, []int{0}
}
func (m *CreateLaptopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLaptopRequest.Unmarshal(m, b)
}
func (m *CreateLaptopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLaptopRequest.Marshal(b, m, deterministic)
}
func (m *CreateLaptopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLaptopRequest.Merge(m, src)
}
func (m *CreateLaptopRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLaptopRequest.Size(m)
}
func (m *CreateLaptopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLaptopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLaptopRequest proto.InternalMessageInfo

func (m *CreateLaptopRequest) GetLaptop() *Laptop {
	if m != nil {
		return m.Laptop
	}
	return nil
}

type CreateLaptopResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLaptopResponse) Reset()         { *m = CreateLaptopResponse{} }
func (m *CreateLaptopResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLaptopResponse) ProtoMessage()    {}
func (*CreateLaptopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9cf9ee0377190e0, []int{1}
}
func (m *CreateLaptopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLaptopResponse.Unmarshal(m, b)
}
func (m *CreateLaptopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLaptopResponse.Marshal(b, m, deterministic)
}
func (m *CreateLaptopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLaptopResponse.Merge(m, src)
}
func (m *CreateLaptopResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLaptopResponse.Size(m)
}
func (m *CreateLaptopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLaptopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLaptopResponse proto.InternalMessageInfo

func (m *CreateLaptopResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SearchLaptopRequest struct {
	Filter               *Filter  `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchLaptopRequest) Reset()         { *m = SearchLaptopRequest{} }
func (m *SearchLaptopRequest) String() string { return proto.CompactTextString(m) }
func (*SearchLaptopRequest) ProtoMessage()    {}
func (*SearchLaptopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9cf9ee0377190e0, []int{2}
}
func (m *SearchLaptopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchLaptopRequest.Unmarshal(m, b)
}
func (m *SearchLaptopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchLaptopRequest.Marshal(b, m, deterministic)
}
func (m *SearchLaptopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchLaptopRequest.Merge(m, src)
}
func (m *SearchLaptopRequest) XXX_Size() int {
	return xxx_messageInfo_SearchLaptopRequest.Size(m)
}
func (m *SearchLaptopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchLaptopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchLaptopRequest proto.InternalMessageInfo

func (m *SearchLaptopRequest) GetFilter() *Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type SearchLaptopResponse struct {
	Laptop               *Laptop  `protobuf:"bytes,1,opt,name=laptop,proto3" json:"laptop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchLaptopResponse) Reset()         { *m = SearchLaptopResponse{} }
func (m *SearchLaptopResponse) String() string { return proto.CompactTextString(m) }
func (*SearchLaptopResponse) ProtoMessage()    {}
func (*SearchLaptopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9cf9ee0377190e0, []int{3}
}
func (m *SearchLaptopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchLaptopResponse.Unmarshal(m, b)
}
func (m *SearchLaptopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchLaptopResponse.Marshal(b, m, deterministic)
}
func (m *SearchLaptopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchLaptopResponse.Merge(m, src)
}
func (m *SearchLaptopResponse) XXX_Size() int {
	return xxx_messageInfo_SearchLaptopResponse.Size(m)
}
func (m *SearchLaptopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchLaptopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchLaptopResponse proto.InternalMessageInfo

func (m *SearchLaptopResponse) GetLaptop() *Laptop {
	if m != nil {
		return m.Laptop
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateLaptopRequest)(nil), "pc.CreateLaptopRequest")
	proto.RegisterType((*CreateLaptopResponse)(nil), "pc.CreateLaptopResponse")
	proto.RegisterType((*SearchLaptopRequest)(nil), "pc.SearchLaptopRequest")
	proto.RegisterType((*SearchLaptopResponse)(nil), "pc.SearchLaptopResponse")
}

func init() { proto.RegisterFile("labtop_service.proto", fileDescriptor_c9cf9ee0377190e0) }

var fileDescriptor_c9cf9ee0377190e0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xbd, 0x4e, 0x86, 0x30,
	0x14, 0x4d, 0x19, 0x48, 0xbc, 0x12, 0x87, 0xda, 0x44, 0xc2, 0x64, 0x3a, 0x18, 0x27, 0x62, 0x70,
	0xd2, 0xcd, 0x90, 0x38, 0x39, 0xc1, 0x03, 0x90, 0x52, 0xae, 0xda, 0x04, 0x6d, 0x6d, 0xab, 0x6f,
	0xe3, 0xbb, 0x7e, 0xa1, 0xed, 0x00, 0x81, 0xe1, 0x5b, 0xcf, 0x4f, 0xcf, 0x39, 0xb7, 0xc0, 0x66,
	0x31, 0x7a, 0x6d, 0x06, 0x87, 0xf6, 0x4f, 0x49, 0xac, 0x8d, 0xd5, 0x5e, 0xd3, 0xcc, 0xc8, 0xaa,
	0x98, 0x85, 0xf1, 0xda, 0x44, 0xa4, 0x62, 0xef, 0x6a, 0xf6, 0x68, 0x87, 0x2f, 0x74, 0x4e, 0x7c,
	0x24, 0x1d, 0x7f, 0x82, 0xeb, 0xd6, 0xa2, 0xf0, 0xf8, 0x16, 0xb4, 0x1d, 0xfe, 0xfc, 0xa2, 0xf3,
	0x94, 0x43, 0x1e, 0xcd, 0x25, 0xb9, 0x25, 0xf7, 0x97, 0x0d, 0xd4, 0x46, 0xd6, 0x49, 0x92, 0x18,
	0x7e, 0x07, 0x6c, 0x6b, 0x75, 0x46, 0x7f, 0x3b, 0xa4, 0x57, 0x90, 0xa9, 0x29, 0xf8, 0x2e, 0xba,
	0x4c, 0x4d, 0x4b, 0x44, 0x8f, 0xc2, 0xca, 0xcf, 0x5d, 0x44, 0x6c, 0xb4, 0x8e, 0x78, 0x0d, 0x48,
	0x97, 0x18, 0xfe, 0x0c, 0x6c, 0x6b, 0x4d, 0x11, 0x67, 0xd4, 0x6b, 0xfe, 0xc9, 0x76, 0x5a, 0x1f,
	0xef, 0x43, 0x5f, 0xa0, 0x58, 0xc3, 0xf4, 0x66, 0xf1, 0x1e, 0xdc, 0xa0, 0x2a, 0xf7, 0x44, 0x8a,
	0x6f, 0xa1, 0x58, 0xd7, 0x8a, 0x4f, 0x1c, 0x6c, 0x8c, 0x4f, 0x1c, 0x2d, 0x78, 0x20, 0x63, 0x1e,
	0x3e, 0xe0, 0xf1, 0x14, 0x00, 0x00, 0xff, 0xff, 0x51, 0xd2, 0x0a, 0x82, 0xc0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CreateLaptopServiceClient is the client API for CreateLaptopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CreateLaptopServiceClient interface {
	CreateLaptop(ctx context.Context, in *CreateLaptopRequest, opts ...grpc.CallOption) (*CreateLaptopResponse, error)
	SearchLaptop(ctx context.Context, in *SearchLaptopRequest, opts ...grpc.CallOption) (CreateLaptopService_SearchLaptopClient, error)
}

type createLaptopServiceClient struct {
	cc *grpc.ClientConn
}

func NewCreateLaptopServiceClient(cc *grpc.ClientConn) CreateLaptopServiceClient {
	return &createLaptopServiceClient{cc}
}

func (c *createLaptopServiceClient) CreateLaptop(ctx context.Context, in *CreateLaptopRequest, opts ...grpc.CallOption) (*CreateLaptopResponse, error) {
	out := new(CreateLaptopResponse)
	err := c.cc.Invoke(ctx, "/pc.CreateLaptopService/CreateLaptop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *createLaptopServiceClient) SearchLaptop(ctx context.Context, in *SearchLaptopRequest, opts ...grpc.CallOption) (CreateLaptopService_SearchLaptopClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CreateLaptopService_serviceDesc.Streams[0], "/pc.CreateLaptopService/SearchLaptop", opts...)
	if err != nil {
		return nil, err
	}
	x := &createLaptopServiceSearchLaptopClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CreateLaptopService_SearchLaptopClient interface {
	Recv() (*SearchLaptopResponse, error)
	grpc.ClientStream
}

type createLaptopServiceSearchLaptopClient struct {
	grpc.ClientStream
}

func (x *createLaptopServiceSearchLaptopClient) Recv() (*SearchLaptopResponse, error) {
	m := new(SearchLaptopResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CreateLaptopServiceServer is the server API for CreateLaptopService service.
type CreateLaptopServiceServer interface {
	CreateLaptop(context.Context, *CreateLaptopRequest) (*CreateLaptopResponse, error)
	SearchLaptop(*SearchLaptopRequest, CreateLaptopService_SearchLaptopServer) error
}

// UnimplementedCreateLaptopServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCreateLaptopServiceServer struct {
}

func (*UnimplementedCreateLaptopServiceServer) CreateLaptop(ctx context.Context, req *CreateLaptopRequest) (*CreateLaptopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLaptop not implemented")
}
func (*UnimplementedCreateLaptopServiceServer) SearchLaptop(req *SearchLaptopRequest, srv CreateLaptopService_SearchLaptopServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchLaptop not implemented")
}

func RegisterCreateLaptopServiceServer(s *grpc.Server, srv CreateLaptopServiceServer) {
	s.RegisterService(&_CreateLaptopService_serviceDesc, srv)
}

func _CreateLaptopService_CreateLaptop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLaptopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateLaptopServiceServer).CreateLaptop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pc.CreateLaptopService/CreateLaptop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateLaptopServiceServer).CreateLaptop(ctx, req.(*CreateLaptopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreateLaptopService_SearchLaptop_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchLaptopRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CreateLaptopServiceServer).SearchLaptop(m, &createLaptopServiceSearchLaptopServer{stream})
}

type CreateLaptopService_SearchLaptopServer interface {
	Send(*SearchLaptopResponse) error
	grpc.ServerStream
}

type createLaptopServiceSearchLaptopServer struct {
	grpc.ServerStream
}

func (x *createLaptopServiceSearchLaptopServer) Send(m *SearchLaptopResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _CreateLaptopService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pc.CreateLaptopService",
	HandlerType: (*CreateLaptopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLaptop",
			Handler:    _CreateLaptopService_CreateLaptop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchLaptop",
			Handler:       _CreateLaptopService_SearchLaptop_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "labtop_service.proto",
}
