// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hello.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_PC  Person_PhoneType = 0
	Person_AND Person_PhoneType = 1
	Person_IOS Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "PC",
	1: "AND",
	2: "IOS",
}

var Person_PhoneType_value = map[string]int32{
	"PC":  0,
	"AND": 1,
	"IOS": 2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}

func (Person_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{4, 0}
}

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ByeRequest struct {
	Info                 string   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByeRequest) Reset()         { *m = ByeRequest{} }
func (m *ByeRequest) String() string { return proto.CompactTextString(m) }
func (*ByeRequest) ProtoMessage()    {}
func (*ByeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{2}
}
func (m *ByeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByeRequest.Unmarshal(m, b)
}
func (m *ByeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByeRequest.Marshal(b, m, deterministic)
}
func (m *ByeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByeRequest.Merge(m, src)
}
func (m *ByeRequest) XXX_Size() int {
	return xxx_messageInfo_ByeRequest.Size(m)
}
func (m *ByeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByeRequest proto.InternalMessageInfo

func (m *ByeRequest) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type ByeReply struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByeReply) Reset()         { *m = ByeReply{} }
func (m *ByeReply) String() string { return proto.CompactTextString(m) }
func (*ByeReply) ProtoMessage()    {}
func (*ByeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{3}
}
func (m *ByeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByeReply.Unmarshal(m, b)
}
func (m *ByeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByeReply.Marshal(b, m, deterministic)
}
func (m *ByeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByeReply.Merge(m, src)
}
func (m *ByeReply) XXX_Size() int {
	return xxx_messageInfo_ByeReply.Size(m)
}
func (m *ByeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ByeReply.DiscardUnknown(m)
}

var xxx_messageInfo_ByeReply proto.InternalMessageInfo

func (m *ByeReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Person struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32            `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string           `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Type                 Person_PhoneType `protobuf:"varint,4,opt,name=type,proto3,enum=pb.Person_PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{4}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_PC
}

func init() {
	proto.RegisterEnum("pb.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
	proto.RegisterType((*HelloRequest)(nil), "pb.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "pb.HelloReply")
	proto.RegisterType((*ByeRequest)(nil), "pb.ByeRequest")
	proto.RegisterType((*ByeReply)(nil), "pb.ByeReply")
	proto.RegisterType((*Person)(nil), "pb.Person")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x6a, 0xc2, 0x40,
	0x18, 0x84, 0xdd, 0x18, 0x13, 0xfd, 0x2b, 0x12, 0x7e, 0x3c, 0x04, 0x0f, 0x25, 0x2c, 0x58, 0x72,
	0xca, 0xc1, 0x3e, 0x41, 0x6d, 0xc1, 0x7a, 0x69, 0x25, 0xf6, 0x05, 0x56, 0xfc, 0xad, 0x81, 0x98,
	0xdd, 0x26, 0xdb, 0xc3, 0xbe, 0x42, 0xaf, 0x7d, 0xe1, 0xb2, 0x6b, 0xa3, 0xa1, 0xf4, 0x36, 0x33,
	0xfb, 0x31, 0xfc, 0xcc, 0xc2, 0xcd, 0x91, 0xca, 0x52, 0x66, 0xaa, 0x96, 0x5a, 0xa2, 0xa7, 0x76,
	0x9c, 0xc3, 0xf8, 0xd9, 0x46, 0x39, 0x7d, 0x7c, 0x52, 0xa3, 0x11, 0xc1, 0xaf, 0xc4, 0x89, 0x62,
	0x96, 0xb0, 0x74, 0x94, 0x3b, 0xcd, 0xef, 0x00, 0x7e, 0x19, 0x55, 0x1a, 0x8c, 0x21, 0x3c, 0x51,
	0xd3, 0x88, 0xf7, 0x16, 0x6a, 0x2d, 0x4f, 0x00, 0x96, 0x86, 0x3a, 0x4d, 0x45, 0x75, 0x90, 0x6d,
	0x93, 0xd5, 0xfc, 0x16, 0x86, 0x8e, 0xb0, 0x3d, 0x08, 0xfe, 0x5e, 0x68, 0xd1, 0xbe, 0x5b, 0xcd,
	0xbf, 0x19, 0x04, 0x1b, 0xaa, 0x1b, 0x59, 0xfd, 0x77, 0x08, 0x4e, 0xc0, 0x2b, 0xf6, 0xb1, 0x97,
	0xb0, 0x74, 0x90, 0x7b, 0xc5, 0x1e, 0xa7, 0x30, 0xa0, 0x93, 0x28, 0xca, 0xb8, 0xef, 0xa0, 0xb3,
	0xc1, 0x14, 0x7c, 0x6d, 0x14, 0xc5, 0x7e, 0xc2, 0xd2, 0xc9, 0x62, 0x9a, 0xa9, 0x5d, 0x76, 0xee,
	0xcc, 0x36, 0x47, 0x59, 0xd1, 0x9b, 0x51, 0x94, 0x3b, 0x82, 0xcf, 0x61, 0x74, 0x89, 0x30, 0x00,
	0x6f, 0xf3, 0x18, 0xf5, 0x30, 0x84, 0xfe, 0xc3, 0xcb, 0x53, 0xc4, 0xac, 0x58, 0xbf, 0x6e, 0x23,
	0x6f, 0xf1, 0xc5, 0x20, 0x5c, 0xd5, 0x44, 0x9a, 0x6a, 0xcc, 0x60, 0xb8, 0x15, 0xc6, 0xcd, 0x81,
	0x91, 0xad, 0xee, 0xae, 0x37, 0x9b, 0x74, 0x12, 0x55, 0x1a, 0xde, 0xc3, 0x14, 0x82, 0xad, 0x30,
	0x4b, 0x43, 0xe8, 0xde, 0xae, 0xfb, 0xcc, 0xc6, 0x17, 0x7f, 0x26, 0xe7, 0x10, 0xae, 0x48, 0xaf,
	0xab, 0x83, 0x44, 0xb8, 0xde, 0xfc, 0x17, 0xdb, 0x05, 0xee, 0xef, 0xee, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xc9, 0xc2, 0x9e, 0xb8, 0xca, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayBye(ctx context.Context, in *ByeRequest, opts ...grpc.CallOption) (*ByeReply, error)
	GetInfo(ctx context.Context, in *Person, opts ...grpc.CallOption) (*ByeReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/pb.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayBye(ctx context.Context, in *ByeRequest, opts ...grpc.CallOption) (*ByeReply, error) {
	out := new(ByeReply)
	err := c.cc.Invoke(ctx, "/pb.Greeter/SayBye", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetInfo(ctx context.Context, in *Person, opts ...grpc.CallOption) (*ByeReply, error) {
	out := new(ByeReply)
	err := c.cc.Invoke(ctx, "/pb.Greeter/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayBye(context.Context, *ByeRequest) (*ByeReply, error)
	GetInfo(context.Context, *Person) (*ByeReply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedGreeterServer) SayBye(ctx context.Context, req *ByeRequest) (*ByeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayBye not implemented")
}
func (*UnimplementedGreeterServer) GetInfo(ctx context.Context, req *Person) (*ByeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayBye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayBye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Greeter/SayBye",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayBye(ctx, req.(*ByeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Greeter/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetInfo(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "SayBye",
			Handler:    _Greeter_SayBye_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _Greeter_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
